import React from 'react'
import AboutUsBackground from '../assets/AboutUsBackground.jpg'
import '../styles/about.css'
function about() {
  return (
    <div className='about' style={{ backgroundImage: `url(${AboutUsBackground})` }}>
        <h1> About us </h1>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ultrices nulla non lectus ornare facilisis. Sed quis turpis orci. Suspendisse nec erat et erat iaculis aliquet a eu dolor. Fusce vel consectetur mi. Quisque hendrerit posuere sem non accumsan. Nulla facilisi. Aenean efficitur enim quis pellentesque vestibulum. Curabitur semper sem non libero mollis lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse facilisis vitae nisl a gravida. Maecenas sed gravida ex. Sed enim neque, feugiat ac augue sed, euismod luctus ligula. Donec lobortis sollicitudin consectetur. Donec et pulvinar purus. Suspendisse sed pretium urna, a rutrum mauris. Etiam viverra, ante at porta dignissim, erat turpis elementum velit, sed feugiat eros erat vitae augue.
            Duis et imperdiet ex. Aliquam erat volutpat. Phasellus at vulputate ipsum. Ut maximus elementum dictum. Nunc porta lacus mi, a porttitor velit facilisis at. Proin vitae ex vitae nunc congue cursus. Ut massa justo, luctus ut elementum molestie, facilisis eu purus. Sed sagittis leo at est luctus sollicitudin. Vestibulum egestas felis imperdiet risus sagittis tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
            Quisque finibus sapien quis lobortis efficitur. Curabitur facilisis id nisl ut sollicitudin. Aenean sed congue nisi, vel ullamcorper sem. Pellentesque ligula diam, malesuada ut tortor vel, suscipit pulvinar risus. Praesent justo nisl, eleifend vitae volutpat non, egestas ac enim. Etiam urna ex, pharetra ac justo non, rutrum cursus enim. Nulla id est fringilla, ornare risus eget, tincidunt erat. Nulla tincidunt enim id purus ultrices vehicula quis vel lorem. Sed quis orci placerat, sollicitudin sem sed, sollicitudin justo. Nulla egestas turpis ut ipsum hendrerit posuere. Quisque aliquet ex at mi bibendum pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque vitae mauris blandit sem bibendum maximus a eget felis. Integer eget dolor erat. Aenean molestie vel risus ac bibendum. Sed id lacus dignissim, consectetur nunc non, consectetur neque.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Mauris non placerat nunc. Duis blandit ipsum elit, et feugiat quam lobortis sed. Vivamus lectus odio, lobortis sed porttitor id, aliquet et metus. Etiam facilisis massa quam, et tincidunt lorem posuere quis. Proin posuere neque eu massa convallis molestie id in leo. Mauris in tincidunt nibh. Ut tempor at nulla eget viverra. Vestibulum libero neque, vulputate eu elit sed, finibus tempor est. Morbi aliquet consequat libero quis vulputate. Nulla pulvinar volutpat lacus. Donec hendrerit felis non turpis malesuada euismod. Maecenas eu finibus turpis. Sed placerat arcu nisi, et mattis quam efficitur in. Donec vulputate vehicula nunc in semper.
            Suspendisse pulvinar tellus purus, nec porttitor dui sollicitudin in. Duis sed pulvinar nunc, nec interdum sem. In sem nulla, scelerisque varius sodales sed, ultricies dictum neque. Integer pharetra ultricies tellus, et blandit turpis sodales id. Fusce volutpat, lectus mollis sagittis mattis, dui urna porttitor magna, quis porttitor est est ut risus. Maecenas est ipsum, euismod non est vel, semper semper sem. Nulla a tristique tortor, vel tincidunt arcu. Sed imperdiet est quis turpis imperdiet, non consequat risus dapibus. Donec ultricies, est id pellentesque ullamcorper, lacus nulla dapibus leo, eget viverra odio sapien eu elit. Nulla erat tortor, venenatis nec interdum eu, consectetur at enim. Suspendisse gravida sapien placerat, pharetra elit id, porta orci. Donec mattis felis nec consectetur venenatis. Nulla magna mauris, dapibus in sapien quis, lacinia facilisis lacus. Proin placerat lobortis urna sed elementum.</p>
      </div>
  )
}

export default about
